-- [문제 4] 오랜 기간 보호한 동물(2)
-- 입양을 간 동물 중, 보호 기간이 가장 길었던 동물 두 마리의 아이디와 이름을 조회하는 SQL문을 작성해주세요.
-- 이때 결과는 보호 기간이 긴 순으로 조회해야 합니다.

-- ORACLE JOIN 
SELECT ANIMAL_ID, NAME
FROM (
    SELECT O.ANIMAL_ID, O.NAME
    FROM ANIMAL_OUTS O, ANIMAL_INS I
    WHERE O.ANIMAL_ID = I.ANIMAL_ID(+)
      AND O.DATETIME - I.DATETIME IS NOT NULL
    ORDER BY O.DATETIME - I.DATETIME DESC
)
WHERE ROWNUM BETWEEN 1 AND 2

-- OR --

SELECT ANIMAL_ID, NAME
FROM
(
    SELECT A.ANIMAL_ID, A.NAME, A.DATETIME - B.DATETIME
    FROM ANIMAL_OUTS A LEFT JOIN ANIMAL_INS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
    WHERE A.DATETIME - B.DATETIME IS NOT NULL
    ORDER BY A.DATETIME - B.DATETIME DESC
)
WHERE ROWNUM BETWEEN 1 AND 2